- platform: template
  sensors:
    hall_motion_battery_low:
      value_template: '{{ states.zwave.multisensor1_9.attributes.battery_level < 15 }}'
      friendly_name: 'Hall Motion Sensor battery is low'
    front_door_battery_low:
      value_template: '{{ states.zwave.frontd_5.attributes.battery_level < 15 }}'
      friendly_name: 'Front Door battery is low'
    back_door_battery_low:
      value_template: '{{ states.zwave.backd_7.attributes.battery_level < 15 }}'
      friendly_name: 'Back Door battery is low'
    garage_door_battery_low:
      value_template: '{{ states.zwave.garaged_6.attributes.battery_level < 15 }}'
      friendly_name: 'Garage Door battery is low'

- platform: mqtt
  state_topic: "wallpanel/mywallpanel/sensor/motion"
  name: "Motion"
  payload_on: '{"value":true}'
  payload_off: '{"value":false}'
  device_class: motion

- platform: mqtt
  state_topic: "dummy/floorplan/sensor"
  name: "Floorplan"